### PR TITLE
Polkadot v0.9.8

### PR DESCRIPTION
**Pull request by clangenb**
* compiled locally, not checked otherwise yet.

### CODE REVIEW

**Comment by clangenb** [comment]
@brenzi I am uncertain about the runtime-versioning.

**Comment by clangenb** [comment]
I asked about the runtime version because you wanted to tag it to `v0.9.0`. Was that because you thought the version was currently at `v0.8.0` (encointer)?

**Comment by brenzi** [comment]
Actually, as we had a security review of our pallet and the functionality is MVP complete, I think we could also say 1.0.0 and then follow strict semver from there.

as the runtime version is 10 now, I'd suggest to version the collator and the runtime with 1.0.10

**Comment by clangenb** [comment]
Successfully tested local setups with polkadot-launch. Will test manual-runtime upgrade after artifacts are finished.

**Comment by clangenb** [comment]
Tested runtime upgrade according to: https://gist.github.com/clangenb/b3c8d34265254aad8033ed7755d10ec0.

**Review by brenzi — APPROVED** [review]

**Pull request merged**
